Readme template
openMSL/governance-and-documentation pull request #5
Opened 2023-01-09 16:57 UTC by ClemensLinnhoff

This PR fixes issue #2.

- Further descriptions and examples are added to the sections,
- a reference section was added at the end with the IEEE citation style. A native support for bibtex in markdown was not found. There are solutions but they are rather hacky and not straight forward. Therefore the bibliography is set manually.

2023-01-10 06:51 UTC, LukasElster requested changes
See comments in commit.

2023-01-10 06:51 UTC, LukasElster commented on model_readme_template.md
> +Each parameter should have a short description as shown in the following example.
I would add here the necessity to use a table as shown below. Otherwise new models will look different in their readme style.

2023-01-10 06:51 UTC, LukasElster commented on model_readme_template.md
> +## Credits
Should we add, that this part is optional?

2023-01-13 12:33 UTC, jdsika commented
Without native bibtex support for markdown we should not add the bibtex file but just use the IEEE reference

2023-01-30 08:35 UTC, closed without merging